Inventory System/Models/ItemOutput.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Inventory_System.Models
{
    public class ItemOutput:helper.Classes.TableWithDate
    {
        public int ItemOutputId { set; get; }

        [Required(ErrorMessage = "من فضلك ادخل الكميه")]
        public double ItemOutputQuantity { set; get; }

        public int ItemId { set; get; }
        
        public Item Item { set; get; }
               
        public int ProjectId { set; get; }
        
        public Project Project { set; get; }

        //Add department link
        public int? TechnicalDepartmentId { get; set; }

        public TechnicalDepartment TechnicalDepartment { set; get; }

        //Approved with default false
        public bool ItemOutputApproved { get; set; } = false;

        public string Notes { get; set; }
        public int DocCode { set; get; } //رقم المستند

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? ExchangeDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DateCreated { get; set; } = DateTime.Now;

    }
}

Inventory System/Controllers/ItemOutputsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using helper.Classes;
using Inventory_System;
using Inventory_System.Models;
using PagedList;

namespace Inventory_System.Controllers
{
    public class ItemOutputsController : Controller
    {
        private InventoryDB db = new InventoryDB();
        class ProjectMix
        {
            public int ProjectId { get; set; }
            public string ProjectCode { get; set; }
        }
        // GET: ItemOutputs
        [VerifyUser(Roles = "superadmin,warehouse,cost,warehouseaudit")]
        public ActionResult Index(int? page, int? TechnicalDepartmentId, int? ProjectId, int? docNumber, string startDate,string endDate, string showLack = "0")
        {


            ViewBag.showLack = showLack;
            User user;
            Helper.CheckUser(HttpContext, db, out user);
            ViewBag.MainRole = user.Roles;
            int pageNumber =1;
            if(page.HasValue)
            {
                pageNumber = page.Value;
            }

            var itemOutputs = db.ItemOutputs.
                Include(a => a.Project).
                Include(a => a.TechnicalDepartment)
                .Include(a => a.Item.ItemInputs)
                .Include(a => a.Item.ItemReturns)
                .Include(a => a.Item.ItemOutputs)
                .Include(a => a.Item);
            List<ProjectMix> pmix = new List<ProjectMix>(); pmix.Add(new ProjectMix() { });
            foreach (var v in db.Projects.ToList())
            {
                pmix.Add(new ProjectMix()
                {
                    ProjectId = v.ProjectId,
                    ProjectCode = v.ProjectCode + "  -  " + v.ProjectName
                });
            }
            ViewBag.ProjectId = new SelectList(pmix, "ProjectId", "ProjectCode");
            ViewBag.TechnicalDepartmentId = new SelectList(db.TechnicalDepartments, "TechnicalDepartmentId", "TechnicalDepartmentName");

            //---------------------------------------------------
            var res = itemOutputs.ToList();
            if (TechnicalDepartmentId != null)
                res = res.Where(a => a.TechnicalDepartmentId == TechnicalDepartmentId).ToList();
            if (ProjectId != null)
                res = res.Where(a => a.ProjectId == ProjectId).ToList();
            if (startDate != null && endDate != null)
            {

                res = helper.Classes.Helper.FilterByDate<ItemOutput>(startDate, endDate,
                    res.AsQueryable());
            }
            double totalPrices = 0;
            foreach(var item in res.ToList())
            {
                totalPrices += (item.Item.ItemAvgPrice * item.ItemOutputQuantity);
            }
            ViewBag.totalPrices = totalPrices;
            if(docNumber.HasValue)
            {
                res = res.Where(a => a.DocCode == docNumber.Value).ToList();
            }
            
            return View(res.OrderByDescending(a => a.DocCode).ToPagedList(pageNumber, 10000000));
            //if (TechnicalDepartmentId != null && ProjectId != null) 
            //{
            //    var items = db.ItemOutputs.Include(i => i.Project)
            //          .Include(i => i.TechnicalDepartment)
            //          .Where(a => a.TechnicalDepartmentId == TechnicalDepartmentId && a.ProjectId == ProjectId);

            //    ViewBag.ProjectIdv = ProjectId;
            //    ViewBag.TechnicalDepartmentIdv = TechnicalDepartmentId;
            //    return View(items.OrderBy(a => a.DateCreated).ToPagedList(pageNumber, pageSize));
            //}
            //else if (ProjectId == null && TechnicalDepartmentId != null)
            //{
            //    var items = db.ItemOutputs.Include(i => i.TechnicalDepartment)
            //        .Where(a => a.TechnicalDepartmentId == TechnicalDepartmentId);

            //    ViewBag.ProjectIdv = ProjectId;
            //    ViewBag.TechnicalDepartmentIdv = TechnicalDepartmentId;
            //    return View(items.OrderBy(a => a.DateCreated).ToPagedList(pageNumber, pageSize));
            //}
            //else if(ProjectId !=null && TechnicalDepartmentId ==null)
            //{
            //    var items = db.ItemOutputs.Include(i => i.Project)
            //       .Where(a => a.ProjectId == ProjectId);

            //    ViewBag.ProjectIdv = ProjectId;
            //    ViewBag.TechnicalDepartmentIdv = TechnicalDepartmentId;

            //    return View(items.OrderBy(a => a.DateCreated).ToPagedList(pageNumber, pageSize));
            //}
            //else
            //    return View(db.ItemOutputs.OrderBy(a => a.DateCreated).ToPagedList(pageNumber, pageSize));

        }

        [VerifyUser(Roles = "superadmin,warehouse,cost,warehouseaudit")]
        public ActionResult warehouse(int? TechnicalDepartmentId, int? ProjectId)
        {
            
            return ReturnWarehouse(TechnicalDepartmentId,ProjectId);
        }
        [VerifyUser(Roles = "superadmin,warehouse,cost,warehouseaudit")]
        ActionResult ReturnWarehouse(int? TechnicalDepartmentId, int? ProjectId)
        {
            if (ProjectId != null)
            {
                ViewBag.prid = ProjectId;
            }
            var itemOutputs = db.ItemOutputs.Include(i => i.Item).Include(i => i.Project).Include(i => i.TechnicalDepartment).Where(a => a.ItemOutputApproved == false);
            List<ProjectMix> pmix = new List<ProjectMix>();
            foreach (var v in db.Projects.ToList())
            {
                pmix.Add(new ProjectMix()
                {
                    ProjectId = v.ProjectId,
                    ProjectCode = v.ProjectCode + "  -  " + v.ProjectName
                });
            }
            ViewBag.ProjectId = new SelectList(pmix, "ProjectId", "ProjectCode");
            ViewBag.TechnicalDepartmentId = new SelectList(db.TechnicalDepartments, "TechnicalDepartmentId", "TechnicalDepartmentName");
            if (TechnicalDepartmentId != null)
                itemOutputs = itemOutputs.Where(a => a.TechnicalDepartmentId == TechnicalDepartmentId);
            if (ProjectId != null)
                itemOutputs = itemOutputs.Where(a => a.ProjectId == ProjectId);
            return View("warehouse",itemOutputs.OrderByDescending(a => a.DocCode).ToList());
        }

        [HttpPost]
        [VerifyUser(Roles = "superadmin,warehouse,cost,warehouseaudit")]
        public ActionResult Approve(int[] ItemApproved,double[] ItemQ, int[] ItemDoc)
        {
            if (ItemApproved != null)
            {
                double qToAdd = 0;
                int outputIdToAdd = 0;
                List<int> itemsOut = new List<int>();
                List<int> itemsOutNo = new List<int>();
                using (var scope = new TransactionScope(TransactionScopeOption.Required,
        new TransactionOptions { IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted }))
                {
                    int inddd = 0;
                    foreach (var v in ItemApproved)
                    {
                        var res = db.ItemOutputs.Include(a => a.Item)
                            .Include(a => a.Item.ItemInputs)
                            .Include(a => a.Item.ItemOutputs)
                            .Include(a => a.Item.ItemReturns)
                            .Single(a => a.ItemOutputId == v);

                        var AvailableQnt = (res.Item.ItemInputs.Sum(a => a.ItemQuantity)
                            -
                            res.Item.ItemOutputs.Where(a => a.ItemOutputApproved).Sum(a => a.ItemOutputQuantity))
                            + res.Item.ItemReturns.Where(a=>a.projectId!=null).Sum(a => a.ItemQuantity)
                            - res.Item.ItemReturns.Where(a => a.projectId == null).Sum(a => a.ItemQuantity);
                        if (ItemQ[inddd] <= AvailableQnt)
                        {
                            if (res != null)
                            {
                                res.ItemOutputApproved = true;
                                res.ExchangeDate = DateTime.Now;
                                res.DocCode = ItemDoc[inddd];
                                db.Items.Find(res.ItemId).ItemQuantityWithdraw += ItemQ[inddd];//res.ItemOutputQuantity;
                                if(ItemQ[inddd]!=res.ItemOutputQuantity)
                                {
                                    var diff = res.ItemOutputQuantity - ItemQ[inddd];
                                    res.ItemOutputQuantity = ItemQ[inddd];
                                    db.ItemOutputs.Add(new ItemOutput()
                                    {
                                        ItemId = res.ItemId,
                                        ItemOutputQuantity = diff,
                                        ProjectId = res.ProjectId,
                                        TechnicalDepartmentId = res.TechnicalDepartmentId
                                    });
                                }
                            }
                            itemsOut.Add(v);
                        }
                        else
                        {
                            outputIdToAdd = v;
                            qToAdd = ItemQ[inddd] - AvailableQnt;
                            ViewBag.msg = " هذه الكميه غير متاحه";
                            break;
                        }
                        inddd++;
                    }
                    if (qToAdd == 0)
                    {
                        db.SaveChanges();
                    }

                    scope.Complete();
                }
                if(qToAdd!=0)
                {
                    if (db.DemandItems.Where(a => a.ItemOutputId == outputIdToAdd).ToList().Count() == 0)
                    {

Inventory System/Views/ItemOutputs/Create.cshtml
@model Inventory_System.Models.ItemOutput

@{
    ViewBag.Title = "اضافه طلب جديد";
    var currentRoleNow = ((Inventory_System.Models.User)ViewBag.mainUser).Roles;
    if (currentRoleNow == "warehouse")
    {
        Layout = "~/Views/Shared/_LayoutWarhouse.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutPlanning.cshtml";
    }

}

<h2>اضافه طلب جديد</h2>
<br />



<div class="form-horizontal">
    @*<h4>ItemOutput</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @*<div class="col-md-4 text-right">
                @Html.DropDownListFor(model => model.Item.ItemSubCategory.ItemCategoryId, ViewBag.ItemCategory as SelectList, "اختار الصنف", htmlAttributes: new { @class = "form-control", @id = "ItemCategoryId" })
                @Html.ValidationMessageFor(model => model.Item.ItemSubCategory.ItemCategory.ItemCategoryName, "", new { @class = "text-danger" })
            </div>
            @Html.Label("نوع الصنف", htmlAttributes: new { @class = "control-label col-md-2" })

        </div>*@

    @if (ViewBag.prid != null)
    {
        <input type="hidden" value="@ViewBag.prid" name="ProjectId" id="ProjectId" />
    }
    else
    {
        <div class="form-group">
            <div class="col-md-10 text-right">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control", @id = "ProjectId" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
            @Html.Label("كود المشروع", htmlAttributes: new { @class = "control-label col-md-2" })

        </div>
        <div class="form-group">


            <div class="col-md-10 text-right">
                @Html.Label("_", htmlAttributes: new { @Id = "CatName" })
            </div>
            @Html.Label("إسم الصنف", htmlAttributes: new { @class = "control-label col-md-2" })

        </div>


        <div class="form-group">


            <div class="col-md-10 text-right">
                @Html.Label("_", htmlAttributes: new { @Id = "SubCatName" })
            </div>


            @Html.Label("نوع الصنف", htmlAttributes: new { @class = "control-label col-md-2" })

        </div>
    }
    <div class="form-group">
        <div class="col-md-10 text-right">
            @Html.DropDownList("TechnicalDepartmentId", null, htmlAttributes: new { @class = "form-control", @id = "TechnicalDepartmentId" })
            @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
        </div>
        @Html.Label("القسم", htmlAttributes: new { @class = "control-label col-md-2" })
    </div>

    <div class="form-group">
        <div class="col-md-6 text-right">
            <span id="QuantArea"></span>

        </div>
        <div class="col-md-4 text-right">
            @Html.DropDownList("ItemId", null, htmlAttributes: new { @class = "form-control", @id = "ItemId" })
            @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
        </div>
        @Html.Label("إسم الخامة", htmlAttributes: new { @class = "control-label col-md-2" })

    </div>

    <div class="form-group">
        <div class="col-md-6 text-right">
            <span id="UnitArea"></span>

        </div>
        <div class="col-md-4 text-right">
            @Html.EditorFor(model => model.ItemOutputQuantity, new { htmlAttributes = new { @class = "form-control", @id = "_ItemOutputQuantity" } })
            @Html.ValidationMessageFor(model => model.ItemOutputQuantity, "", new { @class = "text-danger" })
        </div>
        @Html.Label("الكميه", htmlAttributes: new { @class = "control-label col-md-2" })
    </div>

    <div class="form-group">
        <div class="col-md-6 text-right">
            <span id="NotesArea"></span>

        </div>
        <div class="col-md-4 text-right">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", @id = "Notes" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
        @Html.Label("الملاحظات", htmlAttributes: new { @class = "control-label col-md-2" })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" onclick="handleAddingItem()" value="اضافه" class="btn btn-default" />
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="divReal">
        <table class="table">
            <tr id="headerArea">
                @*<th class="text-center">
                        كود المشروع
                    </th>*@
                <th class="text-center">
                    إسم الخامة
                </th>
                <th class="text-center">
                    القسم
                </th>
                <th class="text-center">
                    الكميه
                </th>


            </tr>



        </table>
        <div id="finalDiv" style="display:none;">

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="حفظ" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@*<div>
        @Html.ActionLink("الرجوع لقائمه الأذونات", "technicallist")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<link href="~/Content/css/select2.css" rel="stylesheet" />
<script src="~/Scripts/select2.min.js"></script>

<script>
    var allItems = @Html.Raw(ViewBag.allItems);
    $("#ItemId").select2({
        placeholder: "اختارالمنتج",
        allowClear: true
    });
    $("#ItemId").change(function () {
        for (var i = 0; i < allItems.length; i++) {
            if (allItems[i].ItemId == parseInt($("#ItemId").val())) {
                $("#UnitArea").html(allItems[i].ItemUnit);
                $("#QuantArea").html(allItems[i].ItemReminder);
            }
        }
        $.get("/ItemInputs/GetParents?id=" + $("#ItemId").val(), null, function (data) {
            console.log(data);
            $("#ItemUnit").val(data[2]);
            $("#CatName").text(data[1]);
            $("#SubCatName").text(data[0]);
        });

    });
</script>



<script>
    
    
    $("#ProjectId").select2({
        placeholder: "اختارالمشروع",
        allowClear: true
    });
</script>

<script>
    $("#DepartmentId").select2({
        placeholder: "اختر القسم",
        allowClear: true
    });
</script>
<script>
    function handleAddingItem() {
        if ($("#ProjectId").val() == "null")
            return;
        if ($("#ProjectId").val() == "0")
            return;
        if ($("#ItemId").val() == "null")
            return;

        if ($("#ItemId").val() == "")
            return;

        if ($("#_ItemOutputQuantity").val() == "null")
            return;
        if ($("#_ItemOutputQuantity").val() == "")
            return;

        //"<td class='text-center'>" +
        //    $("#ProjectId").val() +
        //    "</td>" +
        var toAdd = "<tr>" +

            '<td class="text-center">' +
            $("#ItemId option:selected").text() +
            "</td>" +
            '<td class="text-center">' +
            "" +
            "</td>" +
            '<td class="text-center">' +
            $("#_ItemOutputQuantity").val() +
            "</td>" +
            "</tr>";
        var toAdd2 = "<input name='ItemId' value='" + $("#ItemId").val() + "' />" +
            "<input name='ProjectId' value='" + $("#ProjectId").val() + "' />" +
            "<input name='ItemOutputQuantity' value='" + $("#_ItemOutputQuantity").val() + "' />" +
            "<input name='_Notes' value='" + $("#Notes").val() + "' />" +
            "<input name='TechnicalDepartmentId' value='' />";
        $(toAdd).insertAfter("#headerArea");
        $("#Notes").val("");
        $("#finalDiv").append(toAdd2);
    }
</script>

Inventory System/Views/ItemOutputs/Delete.cshtml
@model Inventory_System.Models.ItemOutput

@{
    ViewBag.Title = "حذف بيانات التصريح";
    if (((Inventory_System.Models.User)ViewBag.mainUser).Roles == "projectplanning")
    {
        Layout = "~/Views/Shared/_LayoutPlanning.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutWarhouse.cshtml";
    }
}

<h2>حذف بيانات التصريح</h2>

<h3>هل  نريد حذف هذا التصريح؟</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.DisplayNameFor(model => model.ItemId)

    <div>
        <hr />
        <dl>

            <dt>
                @Html.DisplayName("اسم المشروع")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Project.ProjectName)
            </dd>

            <dt>
                @Html.DisplayName("المنتج")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Item.ItemName)
            </dd>

            <dt>
                @Html.DisplayName("الكميه")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemOutputQuantity)
            </dd>



        </dl>

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("الرجوع لقائمه الأذونات", "Index")
        </div>
    </div>
}

Inventory System/Views/ItemOutputs/Details.cshtml
@model Inventory_System.Models.ItemOutput

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutTechnical.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ItemOutput</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Item.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemOutputQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemOutputQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemOutputId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory System/Views/ItemOutputs/warehouse.cshtml
@model IEnumerable<Inventory_System.Models.ItemOutput>

@{
    ViewBag.Title = "أذون الصرف";
    Layout = "~/Views/Shared/_LayoutWarhouse.cshtml";
}

<h2>أذون الصرف</h2>
<br />

@if (ViewBag.mainUser != null)
{
    if (((Inventory_System.Models.User)ViewBag.mainUser).Roles == "warehouse")
    {
        <p>
            @Html.ActionLink("طلب جديد", "Create", null, new { id = "CreateLink" })
        </p>
    }
}
<p>

    @using (Html.BeginForm())
    {
        <table>

            <tr class=" text-right">
                @*<th class="col-md-2 text-right">
                        @Html.DropDownList("TechnicalDepartmentId", ViewBag.TechnicalDepartmentId as SelectList, null, htmlAttributes: new { @class = "form-control", @id = "TechnicalDepartmentId" })



                    </th>*@
                <th class="col-md-2 text-right">


                    @Html.DropDownList("ProjectId", ViewBag.ProjectId as SelectList, null, htmlAttributes: new { @class = "form-control", @id = "ProjectId" })

                </th>
                <th class="col-md-1 text-right"><input type="submit" value="بحث" /></th>
            </tr>
        </table>
    }


</p>


<br />




@using (Html.BeginForm("Approve", "ItemOutputs"))
{

    <table class="table">
        <tr>
            <th class="text-center">
                @Html.DisplayName("كود المشروع")
            </th>
            <th class="text-center">
                @Html.DisplayName("اسم المشروع")
            </th>
            <th class="text-center">
                @Html.DisplayName("القسم")
            </th>
            <th class="text-center">
                @Html.DisplayName("بن كود")
            </th>
            <th class="text-center">
                @Html.DisplayName("إسم الخامة")
            </th>
            <th class="text-center">
                @Html.DisplayName("الكميه")
            </th>
            <th class="text-center">
                @Html.DisplayName("ملاحظات")
            </th>
            <th class="text-center">
                @Html.DisplayName("تاريخ الاصدار")
            </th>

            <th class="text-center">
                @Html.DisplayName("صرف؟")
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Project.ProjectCode)
                </td>

                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Project.ProjectName)
                </td>

                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.TechnicalDepartment.TechnicalDepartmentName)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Item.BinCode)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Item.ItemName)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ItemOutputQuantity)
                    @Html.DisplayFor(modelItem => item.Item.ItemUnit)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem=>item.Notes)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>

                <td class="text-center">
                    <input type="checkbox" name="ItemApproved" value="@item.ItemOutputId" onchange="checkIt(this)" />
                    <br /> الكميه<br />
                    <input type="number" name="" value="@item.ItemOutputQuantity" max="@item.ItemOutputQuantity" min="0" step="any" />
                    <br /> رقم المستند<br />
                    <input type="number" name="" value="@item.DocCode"  />
                    @*@Html.DisplayFor(modelItem => item.ItemOutputApproved)*@
                </td>

                @*<td class="text-center">
                        <a>
                            @Html.Label("أوافق")
                        </a>
                    </td>*@

            </tr>
        }
    </table>

    <button type="submit" class="btn btn-primary btn-lg">حفظ</button>

    if (ViewBag.msg != null)
    {
        <script type="text/javascript">

                alert("@ViewBag.msg");


        </script>
    }


}
@section scripts{
    <link href="~/Content/css/select2.min.css" />
    <script src="~/Scripts/select2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <link href="~/Content/css/cs.css" rel="stylesheet" />
    @if (ViewBag.prid != null)
    {
        <script>
            $(document).ready(function () {
                $("#CreateLink").attr("href", '@Url.Action("Create")?prid=@ViewBag.prid');
            });
        </script>
    }
    <script>
        function checkIt(me) {
            
            if (me.checked) {
                $(me).next().next().next().attr('name', 'ItemQ');
            } else {
                $(me).next().next().next().attr('name', '');
            }
            if (me.checked) {
                $(me).next().next().next().next().next().next().attr('name', 'ItemDoc');
            } else {
                $(me).next().next().next().next().next().next().attr('name', '');
            }
        }
        $("#ProjectId").change(function () {

            $("#CreateLink").attr("href", '@Url.Action("Create")?prid=' + $("#ProjectId").val());
});
    </script>
    @*<script>
            $("#TechnicalDepartmentId").select2({
                placeholder: "اختر القسم",
                allowClear: true
            });
            $('#TechnicalDepartmentId').on('select2:select', function (e) {
                $.get("/ItemOutputs/Index", { id: $("#TechnicalDepartmentId").val() }, function (data) {

                });
            })
        </script>

        <script>
            $("#ProjectId").select2({
                placeholder: "اختر مشروع",
                allowClear: true
            });
            $('#ProjectId').on('select2:select', function (e) {
                $.get("/ItemOutputs/Index", { id: $("#ProjectId").val() }, function (data) {

                });
            })
        </script>*@

}